### ISSUE TITLE
error while install

### ISSUE THREAD

**Issue by xoyojank** [aspiers/git-deps#105]
Collecting git-deps
  Using cached git-deps-1.0.1.tar.gz (5.7 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\xoyojank\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xoyojank\\AppData\\Local\\Temp\\pip-install-8npl39ca\\git-deps\\setup.py'"'"'; __file__='"'"'C:\\Users\\xoyojank\\AppData\\Local\\Temp\\pip-install-8npl39ca\\git-deps\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\xoyojank\AppData\Local\Temp\pip-pip-egg-info-cw0l9wbe'
         cwd: C:\Users\xoyojank\AppData\Local\Temp\pip-install-8npl39ca\git-deps\
    Complete output (51 lines):
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: 'c:\users\xoyojank\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xoyojank\\AppData\\Local\\Temp\\pip-wheel-c8n0qh4_\\pypandoc\\setup.py'"'"'; __file__='"'"'C:\\Users\\xoyojank\\AppData\\Local\\Temp\\pip-wheel-c8n0qh4_\\pypandoc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\xoyojank\AppData\Local\Temp\pip-wheel-b3h1a0fp'
           cwd: C:\Users\xoyojank\AppData\Local\Temp\pip-wheel-c8n0qh4_\pypandoc\
      Complete output (8 lines):
      no pandoc found, building platform unspecific wheel...
      use 'python setup.py download_pandoc' to download pandoc.
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for pypandoc
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "c:\users\xoyojank\appdata\local\programs\python\python39\lib\site-packages\setuptools\installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "c:\users\xoyojank\appdata\local\programs\python\python39\lib\subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['c:\\users\\xoyojank\\appdata\\local\\programs\\python\\python39\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\WINDYW~1\\AppData\\Local\\Temp\\tmp1dg0xgv7', '--quiet', 'pypandoc']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xoyojank\AppData\Local\Temp\pip-install-8npl39ca\git-deps\setup.py", line 30, in <module>
        setup_package()
      File "C:\Users\xoyojank\AppData\Local\Temp\pip-install-8npl39ca\git-deps\setup.py", line 18, in setup_package
        setup(
      File "c:\users\xoyojank\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 164, in setup
        _install_setup_requires(attrs)
      File "c:\users\xoyojank\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 159, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\users\xoyojank\appdata\local\programs\python\python39\lib\site-packages\setuptools\dist.py", line 699, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "c:\users\xoyojank\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 779, in resolve
        dist = best[req.key] = env.best_match(
      File "c:\users\xoyojank\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 1064, in best_match
        return self.obtain(req, installer)
      File "c:\users\xoyojank\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 1076, in obtain
        return installer(requirement)
      File "c:\users\xoyojank\appdata\local\programs\python\python39\lib\site-packages\setuptools\dist.py", line 758, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "c:\users\xoyojank\appdata\local\programs\python\python39\lib\site-packages\setuptools\installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['c:\\users\\xoyojank\\appdata\\local\\programs\\python\\python39\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\WINDYW~1\\AppData\\Local\\Temp\\tmp1dg0xgv7', '--quiet', 'pypandoc']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by aspiers** [comment]
Please can you describe the exact steps you used for installation?
