### ISSUE TITLE
Project abandoned? pip install fails (Python 3.10.8)

### ISSUE THREAD

**Issue by vt-alt** [aspiers/git-deps#117]
pip does not install `git-deps` anymore, is the project abandoned completely?
```
$ pip3 install git-deps
Defaulting to user installation because normal site-packages is not writeable
Collecting git-deps
  Downloading git-deps-1.1.0.zip (8.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 4.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [105 lines of output]
      /usr/lib64/python3/site-packages/setuptools/dist.py:756: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!

              ********************************************************************************
              Usage of dash-separated 'author-email' will not be supported in future
              versions. Please use the underscore name 'author_email' instead.

              By 2023-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self.warn_dash_deprecation(opt, section)
      /usr/lib64/python3/site-packages/setuptools/dist.py:756: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!

              ********************************************************************************
              Usage of dash-separated 'home-page' will not be supported in future
              versions. Please use the underscore name 'home_page' instead.

              By 2023-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self.warn_dash_deprecation(opt, section)
      /usr/lib64/python3/site-packages/setuptools/dist.py:756: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!

              ********************************************************************************
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.

              By 2023-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self.warn_dash_deprecation(opt, section)
      /usr/lib64/python3/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      /usr/lib64/python3/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` and ``easy_install``.
              Instead, use pypa/build, pypa/installer, pypa/build or
              other standards-based tools.

              See https://github.com/pypa/setuptools/issues/917 for details.
              ********************************************************************************

      !!
        easy_install.initialize_options(self)
      /usr/lib64/python3/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer, pypa/build or
              other standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        self.initialize_options()
      long_description_markdown_filename: dist = <setuptools.dist.Distribution object at 0x7fad652e0df0>; attr = 'long_description_markdown_filename'; value = 'README.md'
      markdown_filename = '/tmp/.private/vt1/pip-install-qtachtyj/git-deps_39aabcca6bef4101a693455f69230b30/README.md'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/.private/vt1/pip-install-qtachtyj/git-deps_39aabcca6bef4101a693455f69230b30/setup.py", line 30, in <module>
          setup_package()
        File "/tmp/.private/vt1/pip-install-qtachtyj/git-deps_39aabcca6bef4101a693455f69230b30/setup.py", line 18, in setup_package
          setup(
        File "/usr/lib64/python3/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib64/python3/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/usr/lib64/python3/site-packages/setuptools/dist.py", line 497, in __init__
          _Distribution.__init__(
        File "/usr/lib64/python3/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/usr/lib64/python3/site-packages/setuptools/dist.py", line 936, in finalize_options
          ep(self)
        File "/usr/lib64/python3/site-packages/setuptools/dist.py", line 956, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/tmp/.private/vt1/pip-install-qtachtyj/git-deps_39aabcca6bef4101a693455f69230b30/.eggs/setuptools_markdown-0.4.1-py3.10.egg/setuptools_markdown.py", line 43, in long_description_markdown_filename
          output = pypandoc.convert(markdown_filename, 'rst', format='md')
      AttributeError: module 'pypandoc' has no attribute 'convert'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
Python 3.10.8

**Comment by zenspider** [comment]
I'm getting the exact same error but with python 3.11 (installed via homebrew)

**Comment by aspiers** [comment]
Not abandoned!  But haven't had the need to work on it recently.  I just submitted #118 which should fix some issues but probably not the one listed here yet.  However I note that Travis CI is no longer free so we need to transition to GitHub Actions to get working CI again.

**Comment by aspiers** [comment]
I note that you are using the released version 1.1.0 on PyPI.  Can you try with the `tox-py311` branch in #118 instead?

**Comment by aspiers** [comment]
I filed #119 about the Travis CI issue.

**Comment by zenspider** [comment]
I can't find it now. But I found a `pip` command to downgrade pypandoc (or something) to get past this error.

**Comment by mmz-zmm** [comment]
use pip install -U  pypandoc==1.7.0 to skip this error.

**Comment by olejorgenb** [comment]
First of all: thanks for creating this project! I've been wanting something like this a long time.

Any update @aspiers ? I know that it's hard to find time for such projects. I see that quite a few people have added fixes to their own personal branches: https://github.com/aspiers/git-deps/network
