### ISSUE TITLE
ModuleNotFoundError: No module named 'gitutils'

### ISSUE THREAD

**Issue by toabctl** [aspiers/git-deps#72]
I tried to install git-deps via `pip`:
```
(blub) tom@basilikum:~/tmp$ pip install git-deps
Collecting git-deps
  Downloading https://files.pythonhosted.org/packages/15/1e/1da15cccd932612518dd38c16f458f5a78fc3b77ad12896f2255fc0be820/git-deps-1.0.0rc1.tar.gz (12.5MB)
    100% |████████████████████████████████| 12.5MB 1.5MB/s 
Requirement already satisfied: pip>=10.0.1 in ./blub/lib/python3.6/site-packages (from git-deps) (10.0.1)
[...]
```
The installation was successful.

But showing the help throws an exception:
```
(blub) tom@basilikum:~/tmp$ git-deps -h
Traceback (most recent call last):
  File "/home/tom/tmp/blub/bin/git-deps", line 7, in <module>
    from git_deps.cli import run
  File "/home/tom/tmp/blub/lib/python3.6/site-packages/git_deps/cli.py", line 33, in <module>
    from git_deps.server import serve
  File "/home/tom/tmp/blub/lib/python3.6/site-packages/git_deps/server.py", line 4, in <module>
    from gitutils import GitUtils
ModuleNotFoundError: No module named 'gitutils'
```

**Comment by aspiers** [comment]
Yeah, thanks - already noticed that.  Easy to fix but trying to figure out why my local installation didn't ever complain during testing!
