### ISSUE TITLE
Errors encountered installing git-deps under Windows

### ISSUE THREAD

**Issue by johnddx** [aspiers/git-deps#92]
I'm not able to run "pip install git-deps" under Windows 10.

`    error in setup command: Error parsing C:\Users\johndog\AppData\Local\Temp\2\pip-install-_m6ma4lh\git-deps\setup.cfg: UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 910: character maps to <undefined>
`
I ran pip with --no-clean and looked at the setup.cfg, but I didn't see any problems in it (or even a byte 0x9d), so it must be somewhere else than implied by the error message.

```
C:\Users\johnddx>pip install git-deps 
Collecting git-deps
  Using cached https://files.pythonhosted.org/packages/6d/02/b90cfd102dcd6bddaccbaed0b55d7d39cea8fa602c465fb8f35216028ea1/git-deps-1.0.1.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR:

    !!! pandoc not found, long_description is bad, don't upload this to PyPI !!!


    C:\Users\johnddx\AppData\Local\Temp\2\easy_install-vbrkjq5p\pypandoc-1.4\setup.py:16: DeprecationWarning: Due to possible ambiguity, 'convert()' is deprecated. Use 'convert_file()'  or 'convert_text()'.
      long_description = pypandoc.convert('README.md', 'rst')
    See http://johnmacfarlane.net/pandoc/installing.html
    for installation options
    ---------------------------------------------------------------

    zip_safe flag not set; analyzing archive contents...
    pypandoc.__pycache__.__init__.cpython-37: module references __file__

    Installed c:\users\johnddx\appdata\local\temp\2\pip-install-_m6ma4lh\git-deps\.eggs\pypandoc-1.4-py3.7.egg
    Searching for wheel>=0.25.0
    Reading https://pypi.org/simple/wheel/
    Downloading https://files.pythonhosted.org/packages/96/ba/a4702cbb6a3a485239fbe9525443446203f00771af9ac000fa3ef2788201/wheel-0.33.1-py2.py3-none-any.whl#sha256=8eb4a788b3aec8abf5ff68d4165441bc57420c9f64ca5f471f58c3969fe08668
    Best match: wheel 0.33.1
    Processing wheel-0.33.1-py2.py3-none-any.whl
    Installing wheel-0.33.1-py2.py3-none-any.whl to c:\users\johnddx\appdata\local\temp\2\pip-install-_m6ma4lh\git-deps\.eggs
    writing requirements to c:\users\johnddx\appdata\local\temp\2\pip-install-_m6ma4lh\git-deps\.eggs\wheel-0.33.1-py3.7.egg\EGG-INFO\requires.txt

    Installed c:\users\johnddx\appdata\local\temp\2\pip-install-_m6ma4lh\git-deps\.eggs\wheel-0.33.1-py3.7.egg
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "c:\users\johnddx\appdata\local\temp\2\pip-install-_m6ma4lh\git-deps\.eggs\pyscaffold-2.5.11-py3.7.egg\pyscaffold\contrib\pbr\pbr\core.py", line 96, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "c:\users\johnddx\appdata\local\temp\2\pip-install-_m6ma4lh\git-deps\.eggs\pyscaffold-2.5.11-py3.7.egg\pyscaffold\contrib\pbr\pbr\util.py", line 258, in cfg_to_args
        pbr.hooks.setup_hook(config)
      File "c:\users\johnddx\appdata\local\temp\2\pip-install-_m6ma4lh\git-deps\.eggs\pyscaffold-2.5.11-py3.7.egg\pyscaffold\contrib\pbr\pbr\hooks\__init__.py", line 25, in setup_hook
        metadata_config.run()
      File "c:\users\johnddx\appdata\local\temp\2\pip-install-_m6ma4lh\git-deps\.eggs\pyscaffold-2.5.11-py3.7.egg\pyscaffold\contrib\pbr\pbr\hooks\base.py", line 27, in run
        self.hook()
      File "c:\users\johnddx\appdata\local\temp\2\pip-install-_m6ma4lh\git-deps\.eggs\pyscaffold-2.5.11-py3.7.egg\pyscaffold\contrib\pbr\pbr\hooks\metadata.py", line 26, in hook
        self.config['name'], self.config.get('version', None))
      File "c:\users\johnddx\appdata\local\temp\2\pip-install-_m6ma4lh\git-deps\.eggs\pyscaffold-2.5.11-py3.7.egg\pyscaffold\contrib\pbr\pbr\packaging.py", line 798, in get_version
        version = _get_version_from_pkg_metadata(package_name)
      File "c:\users\johnddx\appdata\local\temp\2\pip-install-_m6ma4lh\git-deps\.eggs\pyscaffold-2.5.11-py3.7.egg\pyscaffold\contrib\pbr\pbr\packaging.py", line 766, in _get_version_from_pkg_metadata
        pkg_metadata = email.message_from_file(pkg_metadata_file)
      File "c:\python37\lib\email\__init__.py", line 54, in message_from_file
        return Parser(*args, **kws).parse(fp)
      File "c:\python37\lib\email\parser.py", line 54, in parse
        data = fp.read(8192)
      File "c:\python37\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 910: character maps to <undefined>
    **error in setup command: Error parsing C:\Users\johnddx\AppData\Local\Temp\2\pip-install-_m6ma4lh\git-deps\setup.cfg: UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 910: character maps to <undefined>**
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\johnddx\AppData\Local\Temp\2\pip-install-_m6ma4lh\git-deps\

```

**Comment by jmiguel-hdez** [comment]
i get the same error

**Comment by aspiers** [comment]
Hi, I've just released 1.1.0.  Any chance you could test whether you still see this issue?  Thanks!

**Comment by prrichard** [comment]
Hi, I am getting the error in version 1.1.0.

C:\Users\xyz>pip3 install git-deps
Collecting git-deps
  Downloading https://files.pythonhosted.org/packages/af/b6/a972c2e33471312039eaee79b0f361807aac43a680ea1c69db2c8d87e13a/git-deps-1.1.0.zip (8.1MB)
     |████████████████████████████████| 8.2MB 3.3MB/s
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\xyz\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xy~1\\AppData\\Local\\Temp\\2\\pip-install-dr453odx\\git-deps\\setup.py'"'"'; __file__='"'"'C:\\Users\\xy~1\\AppData\\Local\\Temp\\2\\pip-install-dr453odx\\git-deps\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\xy~1\AppData\Local\Temp\2\pip-install-dr453odx\git-deps\pip-egg-info'
         cwd: C:\Users\xy~1\AppData\Local\Temp\2\pip-install-dr453odx\git-deps\
    Complete output (28 lines):
    zip_safe flag not set; analyzing archive contents...
    pypandoc.__pycache__.__init__.cpython-37: module references __file__

    Installed c:\users\xy~1\appdata\local\temp\2\pip-install-dr453odx\git-deps\.eggs\pypandoc-1.5-py3.7.egg
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "c:\users\xy~1\appdata\local\temp\2\pip-install-dr453odx\git-deps\.eggs\pyscaffold-2.5.11-py3.7.egg\pyscaffold\contrib\pbr\pbr\core.py", line 96, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "c:\users\xy~1\appdata\local\temp\2\pip-install-dr453odx\git-deps\.eggs\pyscaffold-2.5.11-py3.7.egg\pyscaffold\contrib\pbr\pbr\util.py", line 258, in cfg_to_args
        pbr.hooks.setup_hook(config)
      File "c:\users\xy~1\appdata\local\temp\2\pip-install-dr453odx\git-deps\.eggs\pyscaffold-2.5.11-py3.7.egg\pyscaffold\contrib\pbr\pbr\hooks\__init__.py", line 25, in setup_hook
        metadata_config.run()
      File "c:\users\xy~1\appdata\local\temp\2\pip-install-dr453odx\git-deps\.eggs\pyscaffold-2.5.11-py3.7.egg\pyscaffold\contrib\pbr\pbr\hooks\base.py", line 27, in run
        self.hook()
      File "c:\users\xy~1\appdata\local\temp\2\pip-install-dr453odx\git-deps\.eggs\pyscaffold-2.5.11-py3.7.egg\pyscaffold\contrib\pbr\pbr\hooks\metadata.py", line 26, in hook
        self.config['name'], self.config.get('version', None))
      File "c:\users\xy~1\appdata\local\temp\2\pip-install-dr453odx\git-deps\.eggs\pyscaffold-2.5.11-py3.7.egg\pyscaffold\contrib\pbr\pbr\packaging.py", line 798, in get_version
        version = _get_version_from_pkg_metadata(package_name)
      File "c:\users\xy~1\appdata\local\temp\2\pip-install-dr453odx\git-deps\.eggs\pyscaffold-2.5.11-py3.7.egg\pyscaffold\contrib\pbr\pbr\packaging.py", line 766, in _get_version_from_pkg_metadata
        pkg_metadata = email.message_from_file(pkg_metadata_file)
      File "c:\users\xyz\appdata\local\programs\python\python37\lib\email\__init__.py", line 54, in message_from_file
        return Parser(*args, **kws).parse(fp)
      File "c:\users\xyz\appdata\local\programs\python\python37\lib\email\parser.py", line 54, in parse
        data = fp.read(8192)
      File "c:\users\xyz\appdata\local\programs\python\python37\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2916: character maps to <undefined>
    error in setup command: Error parsing C:\Users\xy~1\AppData\Local\Temp\2\pip-install-dr453odx\git-deps\setup.cfg: UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2916: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.3.1; however, version 21.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by aspiers** [comment]
Thanks for the confirmation.  I have no clue how to fix that, and TBH it doesn't sound like it's related to git-deps, but I will leave the issue open anyway.  Perhaps you could try upgrading pip or even Python?

**Comment by johnddx** [comment]
@aspiers can I assume you are not attempting this on Windows?  

It seems Python has different behavior under Windows than other platforms, in that "open()" does not default to utf-8.  There might be a bug somewhere in the package deployment stack (not necessarily in git-deps) with an open() call that doesn't specify utf-8-sig as the default encoding, and that runs into problems with certain content (which _might_ be in git-deps).

**Comment by aspiers** [comment]
That's correct, I use Linux.  I will have to rely on Windows users to help debug this.

Yes, that sounds like a very reasonable possibility.

**Comment by dhebbeker** [comment]
I have the same issue under Windows using pip 25.1.1 and python 3.12

```plain
py -m pip install git-deps
Collecting git-deps
  Using cached git-deps-1.1.0.zip (8.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [57 lines of output]
      ~\AppData\Local\Temp\pip-build-env-_ydyqn6i\normal\Lib\site-packages\pyscaffold\contrib\pbr\pbr\git.py:159: SyntaxWarning: invalid escape sequence '\*'
        msg = msg.replace('*', '\*')
      ~\AppData\Local\Temp\pip-build-env-_ydyqn6i\normal\Lib\site-packages\pyscaffold\contrib\pbr\pbr\git.py:160: SyntaxWarning: invalid escape sequence '\_'
        msg = msg.replace('_', '\_')
      ~\AppData\Local\Temp\pip-build-env-_ydyqn6i\normal\Lib\site-packages\pyscaffold\contrib\pbr\pbr\git.py:161: SyntaxWarning: invalid escape sequence '\`'
        msg = msg.replace('`', '\`')
      ~\AppData\Local\Temp\pip-build-env-_ydyqn6i\normal\Lib\site-packages\pyscaffold\contrib\pbr\pbr\util.py:356: SyntaxWarning: invalid escape sequence '\s'
        requirement_pattern = '(?P<package>[^;]*);?(?P<env_marker>[^#]*?)(?:\s*#.*)?$'
      ~\AppData\Local\Temp\pip-build-env-_ydyqn6i\normal\Lib\site-packages\pyscaffold\contrib\pbr\pbr\util.py:416: SyntaxWarning: invalid escape sequence '\s'
        requirement_pattern = '(?P<package>[^:]*):?(?P<env_marker>[^#]*?)(?:\s*#.*)?$'
      ~\AppData\Local\Temp\pip-build-env-_ydyqn6i\normal\Lib\site-packages\pyscaffold\contrib\setuptools_scm\setuptools_scm\version.py:136: SyntaxWarning: invalid escape sequence '\d'
        prefix, tail = re.match('(.*?)(\d+)$', version).groups()
      ~\AppData\Local\Temp\pip-build-env-_ydyqn6i\normal\Lib\site-packages\pyscaffold\contrib\setuptools_scm\setuptools_scm\hg.py:16: SyntaxWarning: invalid escape sequence '\.'
        " and (merge() or file('re:^(?!\.hgtags).*$'))"
      ~\AppData\Local\Temp\pip-build-env-_ydyqn6i\normal\Lib\site-packages\pyscaffold\pytest_runner.py:38: SetuptoolsDeprecationWarning: The test command is disabled and references to it are deprecated.
      !!

              ********************************************************************************
              Please remove any references to `setuptools.command.test` in all supported versions of the affected package.

              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.
              ********************************************************************************

      !!
        from setuptools.command.test import test as TestCommand
      Error parsing
      Traceback (most recent call last):
        File "~\AppData\Local\Temp\pip-build-env-_ydyqn6i\normal\Lib\site-packages\pyscaffold\contrib\pbr\pbr\core.py", line 96, in pbr
          attrs = util.cfg_to_args(path, dist.script_args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "~\AppData\Local\Temp\pip-build-env-_ydyqn6i\normal\Lib\site-packages\pyscaffold\contrib\pbr\pbr\util.py", line 258, in cfg_to_args
          pbr.hooks.setup_hook(config)
        File "~\AppData\Local\Temp\pip-build-env-_ydyqn6i\normal\Lib\site-packages\pyscaffold\contrib\pbr\pbr\hooks\__init__.py", line 25, in setup_hook
          metadata_config.run()
        File "~\AppData\Local\Temp\pip-build-env-_ydyqn6i\normal\Lib\site-packages\pyscaffold\contrib\pbr\pbr\hooks\base.py", line 27, in run
          self.hook()
        File "~\AppData\Local\Temp\pip-build-env-_ydyqn6i\normal\Lib\site-packages\pyscaffold\contrib\pbr\pbr\hooks\metadata.py", line 25, in hook
          self.config['version'] = packaging.get_version(
                                   ^^^^^^^^^^^^^^^^^^^^^^
        File "~\AppData\Local\Temp\pip-build-env-_ydyqn6i\normal\Lib\site-packages\pyscaffold\contrib\pbr\pbr\packaging.py", line 798, in get_version
          version = _get_version_from_pkg_metadata(package_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "~\AppData\Local\Temp\pip-build-env-_ydyqn6i\normal\Lib\site-packages\pyscaffold\contrib\pbr\pbr\packaging.py", line 766, in _get_version_from_pkg_metadata
          pkg_metadata = email.message_from_file(pkg_metadata_file)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "~\AppData\Local\Programs\Python\Python312\Lib\email\__init__.py", line 53, in message_from_file
          return Parser(*args, **kws).parse(fp)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "~\AppData\Local\Programs\Python\Python312\Lib\email\parser.py", line 52, in parse
          while data := fp.read(8192):
                        ^^^^^^^^^^^^^
        File "~\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2916: character maps to <undefined>
      error in setup command: Error parsing ~\AppData\Local\Temp\pip-install-ogx09r3j\git-deps_c4dd7fd9f089466392921f2dc6c93539\setup.cfg: UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2916: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
